<?php

namespace ForestAdmin\AgentPHP\Tests;

use ForestAdmin\AgentPHP\Agent\Builder\AgentFactory;
use ForestAdmin\AgentPHP\Agent\Facades\Cache;
use ForestAdmin\AgentPHP\DatasourceToolkit\Datasource;
use PHPUnit\Framework\TestCase as BaseTestCase;

class TestCase extends BaseTestCase
{
    public ?AgentFactory $agent = null;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function buildAgent(Datasource $datasource, array $options = [])
    {
        $_SERVER['HTTP_AUTHORIZATION'] = BEARER;
        $_GET['timezone'] = 'Europe/Paris';

        $options = array_merge(
            AGENT_OPTIONS,
            $options
        );

        $this->agent = new AgentFactory($options, []);
        $container = AgentFactory::getContainer();
        $container->set('datasource', $datasource);
        invokeProperty($this->agent, 'container', $container);

        Cache::put('forest.has_permission', true, 10);
    }
}
