<?php

namespace ForestAdmin\AgentPHP\DatasourceCustomizer\Decorators;

use ForestAdmin\AgentPHP\DatasourceCustomizer\Components\Contracts\CollectionContract;
use ForestAdmin\AgentPHP\DatasourceCustomizer\Components\Contracts\DatasourceContract;
use ForestAdmin\AgentPHP\DatasourceCustomizer\Exceptions\ForestException;
use ForestAdmin\AgentPHP\DatasourceToolkit\Datasource;

class DatasourceDecorator extends Datasource
{
    protected DatasourceContract|DatasourceDecorator $childDataSource;

    public function __construct(DatasourceContract|DatasourceDecorator $childDataSource, private string $classCollectionDecorator)
    {
        parent::__construct();
        $this->childDataSource = &$childDataSource;
        // todo
        // this.addCollectionToChildDataSource = childDataSource.addCollection.bind(childDataSource);
        // Reflect.defineProperty(childDataSource, 'addCollection', {
        //      value: this.addCollectionObserver.bind(this),
        // });


    }

    private function addCollectionObserver(Collection $collection): void
    {
        // todo
        // this.addCollectionToChildDataSource(collection);
        $this->addCollection(new CollectionDecorator($collection, $this));
    }

    public function addCollection(CollectionDecorator|CollectionContract $collection): void
    {
//        if ($key = $this->collections->search(fn ($item, $key) => $item->getName() === $collection->getName())) {
//            $this->collections->put($key, $collection);
//        } else {
//            $this->collections->push($collection);
//        }

        if (! $this->collections->has($collection->getName())) {
            $this->collections->put($collection->getName(), $collection);
        }
    }

    public function getCollection(string $name): CollectionContract
    {
        return parent::getCollection($name); // TODO: Change the autogenerated stub
    }

    public function build()
    {
        try {
            foreach ($this->childDataSource->getCollections() as $collection) {
                $this->addCollection(new $this->classCollectionDecorator($collection, $this));
            }
        } catch (\Exception $e) {
            dd($this, $e);
        }
    }
}
