name: Build, Test and Deploy

on:
  push:
    branches:
      - main
      - beta
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer, cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Monorepo-builder merge composer.json
        run: vendor/bin/monorepo-builder merge

      - name: Monorepo-builder validation
        run: vendor/bin/monorepo-builder validate

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Pest PHP tests
        run: vendor/bin/pest --coverage-clover /tmp/clover.xml

      - name: Send coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: /tmp/clover.xml:clover

  split:
    name: Split package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'Agent'
            split_repository: 'php-agent-toolkit'
          - local_path: 'BaseDatasource'
            split_repository: 'php-base-datasource'
          - local_path: 'DatasourceCustomizer'
            split_repository: 'php-datasource-customizer'
          - local_path: 'DatasourceDoctrine'
            split_repository: 'php-datasource-doctrine'
          - local_path: 'DatasourceDummy'
            split_repository: 'php-datasource-dummy'
          - local_path: 'DatasourceToolkit'
            split_repository: 'php-datasource-toolkit'

    needs: [ lint ]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # GITHUB_TOKEN must not be set for the semantic release
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Split packages
        uses: "symplify/monorepo-split-github-action@2.1"
        run: /usr/bin/git config --global --add safe.directory *
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/{{local_path}}" directory
          package_directory: 'packages/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/forestadmin/{{split_repository}} repository
          repository_organization: 'forestadmin'
          repository_name: '${{ matrix.package.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: ${{ secrets.GIT_AUTHOR_NAME }}
          user_email: ${{ secrets.GIT_AUTHOR_EMAIL }}

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy:
    name: Release package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          -
            local_path: 'Agent'
            split_repository: 'php-agent-toolkit'
          -
            local_path: 'BaseDatasource'
            split_repository: 'php-base-datasource'
          -
            local_path: 'DatasourceCustomizer'
            split_repository: 'php-datasource-customizer'
          -
            local_path: 'DatasourceDoctrine'
            split_repository: 'php-datasource-doctrine'
          -
            local_path: 'DatasourceDummy'
            split_repository: 'php-datasource-dummy'
          -
            local_path: 'DatasourceToolkit'
            split_repository: 'php-datasource-toolkit'

    needs: [lint]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    steps:
      - uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
          persist-credentials: false # GITHUB_TOKEN must not be set for the semantic release
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install semantic release dependencies
        run: yarn

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Split packages
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/{{local_path}}" directory
          package_directory: 'packages/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/forestadmin/{{split_repository}} repository
          repository_organization: 'forestadmin'
          repository_name: '${{ matrix.package.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: ${{ secrets.GIT_AUTHOR_NAME }}
          user_email: ${{ secrets.GIT_AUTHOR_EMAIL }}

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
